apiVersion: v1
kind: Secret
metadata:
  name: dremio-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.allFromSecretRef.data.crt }}"
  tls.key: "{{ .Values.allFromSecretRef.data.key }}"
