apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tls-secret
  namespace: default
spec:
  chart:
    spec:
      chart: tls-secret
      sourceRef:
        kind: GitRepository
        name: my-gitops-repo
        namespace: flux-system
      version: "0.1.0"
  interval: 5m
